---
title: "Welcome to My Blog"
description: |
  Welcome to my new blog, My Blog for Cognitive Psychology. I hope you enjoy 
  reading my thoughts about the class and readings!
author:
  - name: Kaitlin Busse 
    url: https://kaitlinabusse.github.io/Kaitlin-s-Blog/
    affiliation: Baruch College/The Graduate Center, CUNY
    affiliation_url: https://www.iopsych-baruch.com/kaitlin-busse
date: 09-09-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

My First Post: Unstructured Writing Assignment

Kolers, P. A., & Roediger, H. L. (1984). Procedures of mind.   Journal of Verbal Learning and Verbal Behavior,   23(4), 425–449.   https://doi.org/10/b7gfkh

**Abstract/Main Idea**: Research commonly studies learning/memory based on info acquisition, storage, and retrieval. This can be problematic because information and the mind are considered to be/have physical-like traits. Article argues for more process-oriented perspective of info processing. With this, mind is seen as a skill of manipulating symbols while skills give a useful framework for understanding important aspects of cognitive processes

**Intro**: Before there was a focus on acquisition, retention, and transfer of learning…but no talk about mind, mentation, info processing, cognition, or memory. 

Outline:
- assumptions of learning and memory assumptions, point out weakness
- propose alt view based on functions of mind as basis of knowledge
- apply view to memory pheno

**Conventional Assumptions of Memory Theories**: “Mental processes are often described as objects or events in an actual physical space as when we speak of storing and organizing memories, of searching through them, or of holding or grasping ideas in our minds; like objects, memories may be lost or hard to find, and so on”

1. Spatial Storage and Search: memory is similar to computer w/ electronic circuits…but should not describe how we function 
2. Structure – Process Distinction: stored in place, but not be productive 
3. Structure: everything is connected…but not sure what we are representing 
4. Process: mind is static object and processes act upon such structures to remember or think…but assumes there’s an exec/constraints in charge which may not be the case
5. Memory as Conscious Recollection: idea we remember but there might be a dissociation between remembering consciously and performance 
6. Semantic Primacy: memory is a byproduct of stages of analysis from shallow surface features to semantic processing of language that’s deeply encoded…but we cant tell how things look/are by looking at them only 

**A Procedural Account of Performance**: Authors propose to “accommodate declarative knowledge in operationalizable terms of actions--the procedures that characterize a person's acquisition and use of knowledge.”
-Declarative knowledge: I know THAT (sem/episode mem)
- Procedural knowledge: I know HOW (procedure w skills)

**Evidence for a Proceduralist View**

- Refutation of Semantic Primacy: W/ procedural account, knowledge acquired through reading or listening depends on cognitive skills of the perceiver. Other issues focused on duration of ST memory, superficial features carry info but not important for LT. “The way that memorability changes as a function of a person's acquiring skill with a symbol set remains to be worked
out. In light of experts' performance, it seems plausible that memorability is a U shaped
 function of skill, increasing again as skill becomes expertise.”

- Means Dependent Knowledge: Claimed people learn from various media by abstracting
and storing their contents but did NOT focus on ways info was acquired. Acquisition and processing of symbols are part of a single indivisible operation.

- Specificity of Transfer: may not  be transfer of muscle groups or formal similarity. Instead, pattern recognition may play a role and w limited transfer. With that, it’s proposed that “positive transfer occurs in relation to the similarity of procedures that two tasks exercise”

- Transfer vs Dissociation of Skills: memory has been traditionally understood as content of mind compared to procedures used to acquire/express knowledge. Propose that “effects of experiences depend upon the procedures used to realize them rather than upon some description of them . . . dissociation does NOT need to be explained, for that is
the natural state of affairs; instead it’s the characteristics of tasks/relations among
underlying procedures-- that need explaining. Responses are specific to skills
in manipulating systems of symbols and there is no necessary connection among responses.

- Consciousness: Focus should be on what one can do than what one knows. Rather than focus on it like a machine, we should focus on consciousness as how sensing organs respond to events (selective monitoring).

**Applications and Extensions**

- Encoding Phenomena: view that repetition of action…generation effect can be
accommodated by a proceduralist account of learning and memory.??
- Interaction of Acquisition and Test: View knowledge is source dependent. More similar procedures during two occasions, more successful performance will be at the later. Learning is specific to exercise of specific skills.
- Recovery: Any complex event has multiple component activities, and more alike they are, the
more alike the behavior will be.

**Reprise**: Belief that mind should be seen as procedures/skills one has on on cog tasks instead of expressed through hypo contents or structures of mind. 
View allows us to view cog process as skills that transfer differentially to new tasks…seen as unifying principle to organize behave patterns of behavior. Also believes complex skills can be seen as made of simpler components. Likewise, logic of transfer of training can be used to identify and study the component skills. Procedural description of mental processes encourages focusing on observables ->> do we see any weakness to this?
“Behavior is situation specific, but its description clearly should have some generality.” Authors believe cog psych should focus on mind as skill in manipulating symbols. This can be seen acquisition of reference (symbol creation), skill in transforming and manipulating symbols (recognition and problem solving), and their application to new occasions (transfer).

“We claim that knowledge of objects is specific to the means of experiencing them” – focus less on abstract and more on ways to which something is learned/acquired…consistency is important for remembering

Overall thoughts: paper was hard to read (really dense). What do we mean by dissociation? I like process/procedural view better in showing complexity and dynamics. But how do we disentangle this. While this is trying to make things less complex and show more procedures and behaviors, how can we test this? What are some examples of this in real world/that we can apply (e.g., education, workplace)?

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Newell, A. (1973).   You can’t play 20 questions with nature and win: Projective comments on the papers of this symposium.   https://doi.org/10/gd4vz2

**Detection**: Psychology deals with phenomena. Pheno are dealt with in many different ways. Psychology also attempts to conceptualize what it is doing (as guide to investigate pheno)…but this is often binary (nature/nurture).

2 constructs drive our experimental style: (1) at a low level, discovery & empirical exploration of pheno and (2) at middle level, formulation of questions to be put to nature that center on the resolution of binary oppositions. At high level, we focus on general big pic questions (how is language used)…but lower levels help us to experiment and give explan to pheno.

BUT clarity is never achieved in science…instead matters get “muddier and muddier” in time. Psych issues have difficulty fading away. View is that science advances with playing 20 questions w nature…(question binary that has an experiment…but question isn’t answered and strat not helpful).

Is it possible to detangle complexity? Do we embrace it?

**Diagnosis**

- On Methods: behavior is programmable. To predict a person one must know: “(1) the goals; (2) the structure of the task environment; and (3) the invariant structure of his processing mechanisms.”…As a result, we are totally engaged in psych exper, in discovery and verification of specific methods used by the subject in doing the exper tasks. The task is to discover the structure that is fixed/invariant to infer theo a method. Given goal of the subject and the task environment faced, we will generate (small) collection of methods likely to be used by person to perform task. After, perform post-hoc analysis of the subject's performance we can settle on method person uses. Without such a framework within which to work, the generation of new methods, hence new explanations, for old phenomena will go on….BUT this doesn’t operate within a frame that constrains what other methods might also be evoked to perform the same task….AS RESULT there’s no model to the control structure (aka specifying the conditional sequence and what it does). As result, if control structure (seen as glue) is missing so not possible to suggest an indefinite sequence of alternative possibilities for how a given task was performed…it prevents theoretical issues from becoming settled.

- Putting it Together: Another issue is that we don’t put results of all experiments together. Hard to integrate everything we know then. Not so much a concern of many methods and findings…it’s more about how they will add up with each other in the future.

**Prognosis (we need things to add up)** 

1) Complete Processing Models: construct complete processing models rather than the partial ones we now do (…given this was 50 years ago, what stops us from doing this now)//helps to address complexity and complication 

2) Analyze a Complex Task: to accept a single complex task and do all of it (aim to focus a series of experimental and theoretical studies around a single complex task, the aim being to demonstrate that one has a sufficient theory of a genuine slab of human behavior) (…but can we ever get to fully address complexity and complex pheno)//acknowledge contradictions to better understand pheno

3) One Program for Many Tasks: stay with the diverse collection of small experimental tasks, but to construct a single system to perform them all (…arent there many different ways to org one thing)//program to perform everything like AI

**Conclusion**: We need to find a way to put everything together. 

Thoughts: We have metas now…but they can be problematic. How do we also ensure quality while sifting through quantity? Where do we go now as a field with combining things? If we do this, wont it just become more complex as we try to intertwine different areas of study together (this might also be a benefit as well).


