---
title: "Semester Project Idea"
description: 
  This is a post about my semester project idea.  
author:
  - name: Kaitlin Busse 
    url: https://kaitlinabusse.github.io/Kaitlin-s-Blog/
    affiliation: Baruch College/The Graduate Center, CUNY
    affiliation_url: https://www.iopsych-baruch.com/kaitlin-busse
date: 09-16-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

## Semester Project Ideas

### Idea 1: Mini Textbook on Learning for Undergraduate Students

I currently teach Psychology of Motivation and Learning class to undergraduate students at Baruch College. While I really like the textbook on motivation, it unfortunately does not cover learning topics. In fact, I have yet to find a book that incorporates both motivation and learning concepts into one. I have not found any open source book chapters that I like that relate to motivation as well for my students to use. 

With that, my goal would be to develop a textbook chapter for my undergraduate students on learning (as it relates to motivation). In doing so, I would want to make an interactive textbook that highlights the ways to which we learn that are packed with motivation examples. This could be helpful to provide a more comprehensive understanding of learning as it relates to motivation. It will help me to understand ways to better teach the topic better to students and also help to provide a resource to future instructors who teach this class. 

**Goals**

- Overview of major theories related to learning

- Include general overview of historical underpinnings of learning theories 

- Connection to motivation and cognition

- Provide examples as it relates to motivation and real-world application 

- Have exercises in the textbook to help students reflect on learning (e.g., short quiz, discussion questions) 

### Idea 2: Literature Review on Decision-Making Processes Related to Fathers’ Utilization of Work-Family Policies 

My research focuses on the predictors and inhibitors of fathers utilization of work-family policies. While I currently use a resource/occupational health-related perspective to examine this, I see a benefit in understanding such research from a cognitive perspective. Specifically, I would want to do a literature review on a judgement/decision-making perspective for why fathers use work-family policies. While I know this is a very targeted topic, I might need to expand on the research to focus on parents in general. In doing so, this project could help me to become more familiar about my research area from another perspective, which will help me become a better researcher. 

**Goals**

- Understand judgement and decision making literature 

- Examine literature as it relates to decision making for work-family policy use

- Synthesize reading into literature review to highlight major themes 

 
